### ISSUE TITLE
Angular JIT compilation failed: '@angular/compiler' not loaded!

### ISSUE THREAD

**Issue by pakro** [arkon/ng-inline-svg#145]
Hello,

after migrating from Angular 8 to 10 some of our applications can't be served anymore. The ng serve process is running without any error (some warnings tho) but when I try to open the app in the browser I'll receive this error:

`Angular JIT compilation failed: '@angular/compiler' not loaded!`

According to the issues https://github.com/angular/angular-cli/issues/16873 and https://github.com/angular/angular/issues/35788 this might be related to libraries not having the necessary module structure for their ngcc. Debugging this in ng_module_factory_registration.ts showed me that it crashes on the ng-inline-svg library.  

Is there any chance you can look into this?

**Comment by arkon** [comment]
Should be fixed in v11.0.0.

On a side note, I hate how every major Angular change requires libraries to be updated. Maybe I'm doing something wrong...

**Comment by erolayhan** [comment]
Hello,
I got this same error too, after updating Angular 8 to 9. (I recommend update step by step. 8 to 9, 9 to 10)

>Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
>  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
>  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
>  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping. 

It is simply says @angular/compiler not loaded. After very long time search, I tried adding _import '@angular/compiler'_  to **main.ts**. And it works for me. 
Hope it is help.

**Comment by ericgopak** [comment]
My code compiled successfully with Angular 10 (`ng build --prod`), but I was getting this error when running the app.

It turned out I've messed up one of my libraries, which I was installing from local disk instead of `npm`. A `package.json` file was missing from a nested `ngx` folder. E.g.:

**This doesn't work**
```
  node_modules/
    ...
    my_library/
      ngx/  <----------- package.json is missing here
      ...
      package.json
```
**This works**
```
  node_modules/
    ...
    my_library/
      ngx/
        package.json
      ...
      package.json
```

Also, you may want to double-check the `name` field in your `package.json` file. If you've forked/modified a library, then you might have changed its scope or name.

**Edit:**
The same could happen when you overwrite packages installed `node_modules/` directly, i.e. modify some files or otherwise mess around with it. Instead of doing so it's safer to separate your changes into a separate package and install it separately.

P.S.: Also see: https://github.com/CharlesElGriego/angular-aot-dynamic-components/issues/6,
