### ISSUE TITLE
Cannot find module '../../node_modules/ng2-inline-svg/lib/inline-svg.directive.ngfactory'

### ISSUE THREAD

**Issue by tadchristiansenli** [arkon/ng-inline-svg#13]
After upgrading to angular 2.1.1 and ng2-inline-svg 1.2.0. I am getting the following errors everywhere I use inline-svg:
`Cannot find module '../../node_modules/ng2-inline-svg/lib/inline-svg.directive.ngfactory'`

Ionic had a similar issue here
https://github.com/driftyco/ionic-app-scripts/issues/214

and they fixed it with this commit:
https://github.com/driftyco/ionic/commit/98d474b879bbc507d294112524c98be762de1d33

I looked in the lib directory (generated js files) and the module exports the directive. I am not sure why this is breaking. Thoughts?

**Comment by arkon** [comment]
I'm not entirely sure, since the factories shouldn't be published anyway.

[This might help](https://forum.ionicframework.com/t/ts-cannot-find-module-app-module-ngfactory/64968)? Or [this](http://stackoverflow.com/a/39867745). [This too](https://github.com/driftyco/ionic/issues/8312).

**Comment by tadchristiansenli** [comment]
I saw the first two, and I am currently reading through the third. I assume you have an app where you can try updating the version to angular 2.1.1 (or 2.1.2) and see if it happens for you as well? If I downgrade angular it works fine. Are you willing to try an ngc build with angular 2.1.1 to see if you can reproduce this?

**Comment by arkon** [comment]
I don't currently have an app that uses AOT compilation (since I use Webpack, and I haven't gotten around to configuring it to use ngc instead of tsc), so unfortunately I can't help much.

**Comment by tadchristiansenli** [comment]
Ok, I will keep digging and let you know what I find.

**Comment by tadchristiansenli** [comment]
It looks like I can get everything working on my side by downgrading to 2.0.1 so I am good for now. I will let you know if I find out what is going on.

**Comment by janein** [comment]
Is there any news on this @tadchristiansenli ?

**Comment by tadchristiansenli** [comment]
Unfortunately no. I reverted back to angular 2.0.1 after failing to figure this out. Let me know if you are able to figure anything out.

**Comment by tadchristiansenli** [comment]
@janein Were you able to figure anything out?

**Comment by arkon** [comment]
@tadchristiansenli @janein How are you guys importing ng2-inline-svg in your project?

**Comment by arkon** [comment]
Note to self: this may be a useful reference
https://github.com/valor-software/ng2-bootstrap/issues/1093

**Comment by tadchristiansenli** [comment]
@arkon 

package.json
`"ng2-inline-svg": "1.2.0"`

app.module.ts:
`import {InlineSVGModule} from "ng2-inline-svg";`
...
```
imports: [
		IonicModule.forRoot(MyApp),
		InlineSVGModule,
...
```

The issue shows up when using AoT and that is probably why you don't see the issue. Ionic 2 uses AoT by default. Let me know if you have any other questions.

Oddly enough it works with angular 2.0.1 but not 2.1.1

**Comment by arkon** [comment]
@tadchristiansenli Could you try v1.3.1 if you have time? It's pretty much just a shot in the dark though...

**Comment by tadchristiansenli** [comment]
Sure, I will give it a shot and let you know.

**Comment by tadchristiansenli** [comment]
I upgraded to ionic rc2 and angular 2.1.1 and v1.3.1 and it looks like the issue has been resolved. I am not sure why moving the module to its own file fixed this though. Thoughts? What made you think to try that?

**Comment by arkon** [comment]
@tadchristiansenli I was reading through the ng2-bootstrap issue I posted earlier, and their issue was resolved when they did that. I suspect it has something to do with how ngc is parsing/generating files based on what's present/imported/exported, but I'm not sure what the exact reasoning is.

Either way, I guess this is resolved. `¯\_(ツ)_/¯`
